# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('contenido', models.CharField(max_length=400)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_publicacion', models.DateField()),
                ('slugs', models.SlugField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
        ),
    ]
