# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_multimedia_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='texto_alternatico',
            new_name='texto_alternativo',
        ),
    ]
