# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170131_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios_Perfil',
            new_name='Perfil',
        ),
    ]
