# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('imagen', models.ImageField(upload_to='img/entradas')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entradas_Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='img/entradas')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas_Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('comentario', models.CharField(max_length=70)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas_Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='entradas',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.Entradas_Categorias'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.Entradas_Comentarios'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.Entradas_Etiquetas'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios'),
        ),
    ]
