# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entradas',
            new_name='Entrada',
        ),
        migrations.RenameModel(
            old_name='Entradas_Categorias',
            new_name='Entradas_Categoria',
        ),
        migrations.RenameModel(
            old_name='Entradas_Comentarios',
            new_name='Entradas_Comentario',
        ),
        migrations.RenameModel(
            old_name='Entradas_Etiquetas',
            new_name='Entradas_Etiqueta',
        ),
    ]
