# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='img/entradas'),
        ),
        migrations.AlterField(
            model_name='productos_categorias',
            name='imagen',
            field=models.ImageField(upload_to='img/entradas'),
        ),
    ]
