# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20170131_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos_Categoria',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Productos_Etiqueta',
            new_name='Etiqueta',
        ),
    ]
