# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20170206_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slugs',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
